Pacific/Pacific/Models/CompanyInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pacific.Models
{
    public class CompanyInfo
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Email { get; set; }   
        public string Mission { get; set; }

        public string AdressLine1 { get; set; }
        public string AdressLine2 { get; set; }
        public string State { get; set; }
        public int ZipCode { get; set; }

        public int Phone { get; set; }
    }
}

Pacific/Pacific/Controllers/CompanyInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pacific.Data;
using Pacific.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pacific.Controllers
{
    public class CompanyInfoController : Controller 
    {
        //Lead Db context dependency injection
        private readonly CompanyInfoDbContext _Context;

        //Cunstructor to requier a Db Context 
        public CompanyInfoController(CompanyInfoDbContext context)
        {
            _Context = context;
        }

        //Index gathering All Leads from Db Context 
        public async Task<IActionResult> Index(string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                return View(await _Context.CompanyInfo.Where(c => c.Name.Contains(searchString)).ToListAsync());
            }

            return View(await _Context.CompanyInfo.ToListAsync());
        }

        //Get: Create
        public IActionResult Create()
        {
            return View();
        }

        //Post: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID, Name, Email, Mission, AdressLine1, AdressLine2, State, ZipCode, Phone")] CompanyInfo companyInfo)
        {
            if (ModelState.IsValid)
            {              
                _Context.Add(companyInfo);
                await _Context.SaveChangesAsync();
                return Redirect("/CompanyInfo/Index");
            }
            return View();
        }

        //Get: edit action
        public async Task<IActionResult> Edit(int? id)
        {
            //check if lead exists
            if (id == null)
            {
                return NotFound();
            }

            //Get selected Lead

            var lead = await _Context.CompanyInfo
                .SingleOrDefaultAsync(l => l.ID == id);

            if (lead == null)
            {
                return NotFound();
            }

            return View(lead);
        }

        //Post: for Edit method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID, Name, Email, Mission, AdressLine1, AdressLine2, State, ZipCode, Phone")] CompanyInfo companyInfo)
        {
            //Check for leads existance
            if (id != companyInfo.ID)
            {
                return NotFound();
            }

            //Apply and save Edits
            if (ModelState.IsValid)
            {
                _Context.Update(companyInfo);
                await _Context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(companyInfo);
        }

        //Get: Delete method that will select a lead to delete
        public async Task<IActionResult> Delete(int? id)
        {
            //Check for leads existance
            if (id == null)
            {
                return NotFound();
            }

            //Retreving the selected lead for deletion
            var lead = await _Context.CompanyInfo
                .SingleOrDefaultAsync(l => l.ID == id);
            if (lead == null)
            {
                return NotFound();
            }

            return View(lead);
        }

        //Post: delete confermation
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //selected lead for deletion
            var lead = await _Context.CompanyInfo
                .SingleOrDefaultAsync(l => l.ID == id);

            //Lead deletion
            _Context.CompanyInfo.Remove(lead);
            await _Context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pacific/Pacific/Views/CompanyInfo/Create.cshtml
@model Pacific.Models.CompanyInfo

@{ 
    Layout = "_Layout";
}

<h1>Create a new CompanyInfo model</h1>
<hr />

<div class="container parallax-section-content">
    <div class="row form-row">
        <div class="col-sm-12 col-md-12 col-lg-4 contact-form-col">
            <form method="post" asp-controller="CompanyInfo" asp-action="Create" class="CompanyCreation-form" style="background-color: black"> @*INLINE STYLE*@

                <div class="form-group">
                    <label asp-for="Name" for="company-name">Name:</label>
                    <input asp-for="Name" type="text" class="form-control" id="company-name" placeholder="exp:name" />
                </div>
                <div class="form-group">
                    <label asp-for="Email" for="company-email">Email:</label>
                    <input asp-for="Email" type="email" class="form-control" id="company-email" placeholder="example@mail.com" />
                </div>
                <div class="form-group">
                    <label asp-for="Mission" for="Mission-message">Mission Statement:</label>
                    <textarea asp-for="Mission" class="form-control" id="Mission-message" rows="5"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="AdressLine1" for="company-adressLine1">AddressLine1:</label>
                    <input asp-for="AdressLine1" type="text" class="form-control" id="company-adressLine1" />
                </div>
                <div class="form-group">
                    <label asp-for="AdressLine2" for="company-adressLine2">AddressLine2:</label>
                    <input asp-for="AdressLine2" type="text" class="form-control" id="company-adressLine2" />
                </div>
                <div class="form-group">
                    <label asp-for="State" for="company-state">State:</label>
                    <input asp-for="State" type="text" class="form-control" id="company-State" />
                </div>
                <div class="form-group">
                    <label asp-for="ZipCode" for="company-zipCode">Zip Code:</label>
                    <input asp-for="ZipCode" type="number" class="form-control" id="company-zipCode" />
                </div>
                <div class="form-group">
                    <label asp-for="Phone" for="company-phone">phone:</label>
                    <input asp-for="Phone" type="number" class="form-control" id="company-phone" />
                </div>
                @*<button type="submit" value="Create" class="btn btn-primary">Submit</button>*@
            </form>
        </div>
    </div>
</div>

Pacific/Pacific/Views/CompanyInfo/Delete.cshtml
@model Pacific.Models.CompanyInfo 

@{ 
    Layout = "_Layout";
}

<div class="container">
    <h2>Delete</h2>
    <hr />
    <dl class="dl-horiszontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mission)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mission)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdressLine1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AdressLine1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AdressLine2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AdressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="@Model.ID" />
        @*<input type="submit" value="Delete" class="btn btn-warning" />*@ |
        <a asp-action="Index">Black To List</a>
    </form>
</div>

Pacific/Pacific/Views/CompanyInfo/Edit.cshtml
@model Pacific.Models.CompanyInfo

@{ 
    Layout = "_Layout";
}

<div class="container">
    <h2>Lead Edit</h2>

    <div class="row">
        <div class="col-sl-12 col-md-12 col-lg-12">
            <form asp-action="Edit">

                @*model only validation*@
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <input asp-for="ID" class="form-control" type="hidden" />

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mission" for="contact-message">Message:</label>
                    <textarea asp-for="Mission" class="form-control" id="contact-message" rows="5"></textarea>
                    <span asp-validation-for="Mission" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdressLine1" class="control-label"></label>
                    <input asp-for="AdressLine1" class="form-control" />
                    <span asp-validation-for="AdressLine1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdressLine2" class="control-label"></label>
                    <input asp-for="AdressLine2" class="form-control" />
                    <span asp-validation-for="AdressLine2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ZipCode" class="control-label"></label>
                    <input asp-for="ZipCode" class="form-control"  />
                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" type="number" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @*<input type="submit" value="Save" class="btn btn-primary" />*@
                </div>
            </form>
        </div>
    </div>
</div>

Pacific/Pacific/Views/CompanyInfo/Index.cshtml
@model IEnumerable<Pacific.Models.CompanyInfo>

@{ 
    Layout = "_Layout";
}
<h2>Company Info</h2>
<hr />
<a asp-controller="CompanyInfo" asp-action="Create">create new</a>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <table class="table">
                <thead style="background-color:black; color:white;"> @*<---------------------------------------- WARNING INLINE STYLE-------> *@
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.Email)</th>
                        <th>@Html.DisplayNameFor(model => model.Mission)</th>
                        <th>@Html.DisplayNameFor(model => model.AdressLine1)</th>
                        <th>@Html.DisplayNameFor(model => model.AdressLine2)</th>
                        <th>@Html.DisplayNameFor(model => model.State)</th>
                        <th>@Html.DisplayNameFor(model => model.ZipCode)</th>
                        <th>@Html.DisplayNameFor(model => model.Phone)</th>
                        <th>Details/Delete</th>
                    </tr>
                </thead>
                <tbody style="background-color:white; color:black;">@*<---------------------------------------- WARNING INLINE STYLE-------> *@
                     @foreach (var item in Model)
                      {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Email)</td>
                            <td>@Html.DisplayFor(modelItem => item.Mission)</td>
                            <td>@Html.DisplayFor(modelItem => item.AdressLine1)</td>
                            <td>@Html.DisplayFor(modelItem => item.AdressLine2)</td>
                            <td>@Html.DisplayFor(modelItem => item.State)</td>
                            <td>@Html.DisplayFor(modelItem => item.ZipCode)</td>
                            <td>@Html.DisplayFor(modelItem => item.Phone)</td>

                            <td>
                                @*<a asp-action="Edit" asp-route-id="@item.ID">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>*@
                            </td>
                        </tr>
                      }
                </tbody>
           </table>
        </div>
     </div>
 </div>